version: 2
updates:
  # Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "src/AzureDevopsTask"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"